spring:
  datasource:
    url: jdbc:h2:mem:picpay
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

authorization: https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc
notification: https://run.mocky.io/v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6